[project]
name = "diskhash"
version = "0.1.0"
description = "磁盘哈希，md5，sha等对磁盘按扇区哈希"
authors = [{ name = "yyjb5", email = "yyjb5@163.com" }]
readme = "README.md"
requires-python = ">= 3.8"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
